version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
        networks:
            - mongo-network

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 8081:8081
        depends_on:
            - mongodb
        networks:
            - mongo-network

volumes:
    mongo-data:

networks:
    mongo-network:
        driver: bridge
